<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>aspnet-PeerReviewApp-87ABFCFD-A0B5-4980-B745-FADE290F34F6</UserSecretsId>
	  <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\**" />
    <Content Remove="Data\Migrations\**" />
    <EmbeddedResource Remove="Data\Migrations\**" />
    <None Remove="Data\Migrations\**" />
    <None Remove="Models\ViewModels\" />
    <None Remove="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.15" />
    <PackageReference Include="SharpZipLib.NETStandard" Version="1.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\files\instructorAssignmentTemplates\" />
    <Folder Include="wwwroot\files\instructorPeerReviewTemplates\" />
    <Folder Include="wwwroot\files\studentSubmittedPeerReviews\" />
    <Folder Include="wwwroot\files\studentSubmittedAssignments\" />
    <Folder Include="Models\ViewModels\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
