// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeerReviewApp.Data;

namespace PeerReviewApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PeerReviewApp.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb7bf870-23b4-49ed-a19b-332f6d5f019a",
                            Email = "testemail1@email.com",
                            EmailConfirmed = false,
                            FirstName = "Jared",
                            InstitutionId = 1,
                            LastName = "Turner",
                            LockoutEnabled = false,
                            Password = "userPassword",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "336a9f7c-9422-46d9-b63a-e73b70e98c6d",
                            TwoFactorEnabled = false,
                            UserName = "JaredT"
                        },
                        new
                        {
                            Id = "B",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca7fb898-d7a9-42ae-a0d0-a7dc233742db",
                            Email = "testemail2@email.com",
                            EmailConfirmed = false,
                            FirstName = "Steve",
                            InstitutionId = 1,
                            LastName = "Jones",
                            LockoutEnabled = false,
                            Password = "userPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd7f2af9-85db-4b6f-b0a7-c6c7c60d9a3a",
                            TwoFactorEnabled = false,
                            UserName = "SteveJ"
                        },
                        new
                        {
                            Id = "C",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7e9c6e3-3aae-4673-a4dd-32695f75133e",
                            Email = "testemail3@email.com",
                            EmailConfirmed = false,
                            FirstName = "Russel",
                            InstitutionId = 1,
                            LastName = "Nelson",
                            LockoutEnabled = false,
                            Password = "userPassword",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65dcb314-39ff-4178-b6a1-504838746148",
                            TwoFactorEnabled = false,
                            UserName = "RusselN"
                        },
                        new
                        {
                            Id = "INSTRUCTOR1A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52f0c6a1-46be-4286-b6c6-8432ed002495",
                            Email = "testemail3@email.com",
                            EmailConfirmed = false,
                            FirstName = "Deedeck",
                            InstitutionId = 1,
                            LastName = "Needles",
                            LockoutEnabled = false,
                            Password = "userPassword",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43d3b3a5-5b1e-46c4-b251-e1407d226e23",
                            TwoFactorEnabled = false,
                            UserName = "Deedeck"
                        },
                        new
                        {
                            Id = "STUDENT1A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db84971c-8ec9-420f-be57-112bfb7a179a",
                            Email = "testemail3@email.com",
                            EmailConfirmed = false,
                            FirstName = "Tyler",
                            InstitutionId = 1,
                            LastName = "Cyler",
                            LockoutEnabled = false,
                            Password = "userPassword",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a09948b-3afd-4f05-b6e0-cad1a5375ae4",
                            TwoFactorEnabled = false,
                            UserName = "TylerC"
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignmentDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeerReviewDueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            AssignmentDueDate = new DateTime(2022, 6, 7, 10, 13, 59, 988, DateTimeKind.Local).AddTicks(4010),
                            AssignmentInstructions = "",
                            AssignmentName = "Lab 1",
                            ClassId = 1,
                            PeerReviewDueDate = new DateTime(2022, 6, 7, 10, 14, 0, 4, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            AssignmentId = 2,
                            AssignmentDueDate = new DateTime(2022, 6, 7, 10, 14, 0, 4, DateTimeKind.Local).AddTicks(7090),
                            AssignmentInstructions = "",
                            AssignmentName = "Lab 2",
                            ClassId = 1,
                            PeerReviewDueDate = new DateTime(2022, 6, 7, 10, 14, 0, 4, DateTimeKind.Local).AddTicks(7100)
                        },
                        new
                        {
                            AssignmentId = 3,
                            AssignmentDueDate = new DateTime(2022, 6, 7, 10, 14, 0, 4, DateTimeKind.Local).AddTicks(7110),
                            AssignmentInstructions = "",
                            AssignmentName = "Lab 3",
                            ClassId = 1,
                            PeerReviewDueDate = new DateTime(2022, 6, 7, 10, 14, 0, 4, DateTimeKind.Local).AddTicks(7110)
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.AssignmentSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrambledName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubmissionId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("AssignmentSubmissions");
                });

            modelBuilder.Entity("PeerReviewApp.Models.AssignmentTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrambledName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("TemplateId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentTemplates");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TermId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TermId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "CS 297 - Programming Capstone - Spring 2022",
                            CourseId = 1,
                            InstructorId = "INSTRUCTOR1A",
                            TermId = 1
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "MATH 203 - Integral Calculus - Spring 2022",
                            CourseId = 2,
                            InstructorId = "INSTRUCTOR1A",
                            TermId = 1
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "CS 275 - Basic Database SQL - Spring 2022",
                            CourseId = 3,
                            InstructorId = "INSTRUCTOR1A",
                            TermId = 1
                        },
                        new
                        {
                            ClassId = 4,
                            ClassName = "CS 275 - Basic Database SQL - Summer 2022",
                            CourseId = 3,
                            InstructorId = "INSTRUCTOR1A",
                            TermId = 2
                        },
                        new
                        {
                            ClassId = 5,
                            ClassName = "MATH 203 - Integral Calculus - Summer 2022",
                            CourseId = 2,
                            InstructorId = "INSTRUCTOR1A",
                            TermId = 2
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "CS 297 - Programming Capstone",
                            DepartmentId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "MATH 203 - Integral Calculus",
                            DepartmentId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "CS 275 - Basic Database SQL",
                            DepartmentId = 1
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartmentId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Computer Science",
                            InstitutionId = 1
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Mathematics",
                            InstitutionId = 1
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "English",
                            InstitutionId = 1
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            ClassId = 1,
                            StudentId = "STUDENT1A"
                        },
                        new
                        {
                            EnrollmentId = 2,
                            ClassId = 2,
                            StudentId = "STUDENT1A"
                        },
                        new
                        {
                            EnrollmentId = 3,
                            ClassId = 3,
                            StudentId = "STUDENT1A"
                        },
                        new
                        {
                            EnrollmentId = 4,
                            ClassId = 4,
                            StudentId = "STUDENT1A"
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignmentSubmissionSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GradeDecimal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("InstructorComment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeerReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeerReviewSubmissionPeerReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GradeId");

                    b.HasIndex("AssignmentSubmissionSubmissionId");

                    b.HasIndex("PeerReviewSubmissionPeerReviewId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructorCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstitutionId");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            InstitutionId = 1,
                            InstitutionName = "Lane Community College",
                            InstructorCode = 1111
                        },
                        new
                        {
                            InstitutionId = 2,
                            InstitutionName = "University of Oregon",
                            InstructorCode = 1111
                        },
                        new
                        {
                            InstitutionId = 3,
                            InstitutionName = "Oregon State University",
                            InstructorCode = 1111
                        },
                        new
                        {
                            InstitutionId = 4,
                            InstitutionName = "Willamette University",
                            InstructorCode = 1111
                        },
                        new
                        {
                            InstitutionId = 5,
                            InstitutionName = "Linn-Benton Community College",
                            InstructorCode = 1111
                        });
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewPartners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Student1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Student2Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Student1Id");

                    b.HasIndex("Student2Id");

                    b.ToTable("prPartners");
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewSubmission", b =>
                {
                    b.Property<int>("PeerReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeerReviewName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeerReviewPartnerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScrambledName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("PeerReviewId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("PeerReviewSubmissions");
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrambledName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .HasColumnType("TEXT");

                    b.HasKey("TemplateId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("PeerReviewTemplates");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TermBeginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TermEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermName")
                        .HasColumnType("TEXT");

                    b.HasKey("TermId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            TermId = 1,
                            InstitutionId = 1,
                            TermBeginDate = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermEndDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermName = "Spring 2022"
                        },
                        new
                        {
                            TermId = 2,
                            InstitutionId = 1,
                            TermBeginDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermEndDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermName = "Summer 2022"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PeerReviewApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PeerReviewApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerReviewApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PeerReviewApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerReviewApp.Models.AppUser", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("PeerReviewApp.Models.Institution", "Institution")
                        .WithMany("Members")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Assignment", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PeerReviewApp.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Assignment", "Assignment")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerReviewApp.Models.AppUser", "Student")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("StudentId");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PeerReviewApp.Models.AssignmentTemplate", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Assignment", "Assignment")
                        .WithMany("AssignmentTemplates")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Class", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerReviewApp.Models.AppUser", "Instructor")
                        .WithMany("Classes")
                        .HasForeignKey("InstructorId");

                    b.HasOne("PeerReviewApp.Models.Term", "Term")
                        .WithMany("Classes")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Course", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Department", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Institution", "Institution")
                        .WithMany("Departments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Enrollment", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerReviewApp.Models.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Grade", b =>
                {
                    b.HasOne("PeerReviewApp.Models.AssignmentSubmission", "AssignmentSubmission")
                        .WithMany("Grades")
                        .HasForeignKey("AssignmentSubmissionSubmissionId");

                    b.HasOne("PeerReviewApp.Models.PeerReviewSubmission", "PeerReviewSubmission")
                        .WithMany("Grades")
                        .HasForeignKey("PeerReviewSubmissionPeerReviewId");

                    b.HasOne("PeerReviewApp.Models.AppUser", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId");

                    b.Navigation("AssignmentSubmission");

                    b.Navigation("PeerReviewSubmission");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewPartners", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerReviewApp.Models.AppUser", "Student1")
                        .WithMany()
                        .HasForeignKey("Student1Id");

                    b.HasOne("PeerReviewApp.Models.AppUser", "Student2")
                        .WithMany()
                        .HasForeignKey("Student2Id");

                    b.Navigation("Class");

                    b.Navigation("Student1");

                    b.Navigation("Student2");
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewSubmission", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Assignment", "Assignment")
                        .WithMany("PeerReviewSubmissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerReviewApp.Models.AppUser", "Student")
                        .WithMany("PeerReviewSubmissions")
                        .HasForeignKey("StudentId");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewTemplate", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Assignment", "Assignment")
                        .WithMany("PeerReviewTemplates")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Term", b =>
                {
                    b.HasOne("PeerReviewApp.Models.Institution", null)
                        .WithMany("Terms")
                        .HasForeignKey("InstitutionId");
                });

            modelBuilder.Entity("PeerReviewApp.Models.AppUser", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("PeerReviewSubmissions");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Assignment", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("AssignmentTemplates");

                    b.Navigation("PeerReviewSubmissions");

                    b.Navigation("PeerReviewTemplates");
                });

            modelBuilder.Entity("PeerReviewApp.Models.AssignmentSubmission", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Institution", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Members");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("PeerReviewApp.Models.PeerReviewSubmission", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("PeerReviewApp.Models.Term", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
